name: yacht
version: 0.0.2
description: Yet another css/html transformer
sdk: '^1.0.0'
dependencies:
  build: any
  # '>=0.9.3'
  barback: any
  csslib: '>=0.13.6'
  html: any
  fs_shim: any
  tekartik_utils:
    git: git://github.com/alextekartik/tekartik_utils.dart
  mustache_no_mirror: any
  markdown: any
  quiver: any
dev_dependencies:
  sass_builder: any
  build_runner: any
  grinder: any
  test: any
  dev_test: any
  process_run: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart

dependency_overrides:
  # build: '>=0.9.3'