name: yacht
version: 0.4.0
description: Yet another css/html transformer
environment:
  sdk: '>=2.7.0-dev <3.0.0'
dependencies:
  build: any
  # '>=0.9.3'
  csslib: '>=0.13.6'
  html: any
  fs_shim: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.9.3'
  markdown: any
  quiver: any
dev_dependencies:
#  sass_builder: any
#  build_runner: any
  grinder: any
  test: any
  dev_test: any
  process_run: any
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'

#dependency_overrides:
  # build: '>=0.9.3'
